spring:
  datasource:
    url: jdbc:mysql://office-server:3306/luffy?useSSL=false
    username: test
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 20
      min-idle: 3
      max-wait: 5000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 100
      validation-query: select 1
      validation-query-timeout: 100
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 30000
      filters: stat
      login-timeout: 5000
      query-timeout: 30000
      stat-view-servlet:
        enabled: true
        login-username: druid
        login-password: 123456
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 3000
    